<h1><center> Machine Learning for Young Data Scientist with Python </center><h1/>
<h3><center> "READ DATA" </center><h3/>


<img src="images/courses.png">

## Read Text File

In [11]:
filename = 'input-data/music.txt'
file = open(filename, mode='r')  # 'r' ทำการเลือกโหมดอ่าน
text = file.read()
file.close()

In [12]:
text

'人はみんな、幸福を願い\nもれずに私もその輪を抜け出せない\n\n誰もが不幸になどなりたくないと\n一つしかないその席を取り合った\n\n選ばれなかった命を\n弔うことすら出来ないままで\n私は今日も白々しく\n生きている\n歌ってる\n顔の見えない誰かに謝りながら\n\nパパとママが愛し合って\n産まれてから20年が経った\n\n何人に愛され\n何人を傷付けてきたんだろう\nわたしは、わたしは、答えられない\n\n選ばれたかった誰かが\n見れたかもしれない光の色を\n私は今日も探している\n死にたいと生きたいの間を\n何度も何度も、行き来しながら\n\n今日は誰かの誕生日で\nそして同時にあなたの命日です\nふとした時に思い出してそして\nいつかは忘れてしまうでしょう\n死のうと思って止めたあとの\n死ねずに吸い込んだこの息で\n私は歌を歌っている\n行きたい場所などどこにもなくて\n生まれた意味はわからなくても\nせめて\u3000せめて\nせめて\u3000せめて\u3000せめて\n\nハッピーバースディ\nハッピーバースディ\nアンハッピーバースディ\nトゥーユー\n\nハッピーバースディ\nハッピーバースディ\nアンハッピーバースディ\nトゥーユー\n\n選ばれなかった命を\n弔うことすら出来ないままで\n私は今日も願っている\n生きていて、と\n死なないで、と\n何度も何度も私は叫ぶよ\n\n選ばれたかった誰かと\nそれでも続いてく世界で今日も\n居場所をずっと探している\n死にたい\u3000と\u3000生きたい\nの間で何度も何度も迷いながら\n\n生まれてきた命には\nせめて愛を、愛\u3000を\nいつか優しくなれるように\nいつか優しい朝が来るように\n\nハッピーバースディ\nハッピーバースディ\nアンハッピーバースディ\nトゥーユー\n\nハッピーバースディ\nハッピーバースディ\nアンハッピーバースディ\nトゥーユー'

In [13]:
text2 = text.split("\n")

In [14]:
text2

['人はみんな、幸福を願い',
 'もれずに私もその輪を抜け出せない',
 '',
 '誰もが不幸になどなりたくないと',
 '一つしかないその席を取り合った',
 '',
 '選ばれなかった命を',
 '弔うことすら出来ないままで',
 '私は今日も白々しく',
 '生きている',
 '歌ってる',
 '顔の見えない誰かに謝りながら',
 '',
 'パパとママが愛し合って',
 '産まれてから20年が経った',
 '',
 '何人に愛され',
 '何人を傷付けてきたんだろう',
 'わたしは、わたしは、答えられない',
 '',
 '選ばれたかった誰かが',
 '見れたかもしれない光の色を',
 '私は今日も探している',
 '死にたいと生きたいの間を',
 '何度も何度も、行き来しながら',
 '',
 '今日は誰かの誕生日で',
 'そして同時にあなたの命日です',
 'ふとした時に思い出してそして',
 'いつかは忘れてしまうでしょう',
 '死のうと思って止めたあとの',
 '死ねずに吸い込んだこの息で',
 '私は歌を歌っている',
 '行きたい場所などどこにもなくて',
 '生まれた意味はわからなくても',
 'せめて\u3000せめて',
 'せめて\u3000せめて\u3000せめて',
 '',
 'ハッピーバースディ',
 'ハッピーバースディ',
 'アンハッピーバースディ',
 'トゥーユー',
 '',
 'ハッピーバースディ',
 'ハッピーバースディ',
 'アンハッピーバースディ',
 'トゥーユー',
 '',
 '選ばれなかった命を',
 '弔うことすら出来ないままで',
 '私は今日も願っている',
 '生きていて、と',
 '死なないで、と',
 '何度も何度も私は叫ぶよ',
 '',
 '選ばれたかった誰かと',
 'それでも続いてく世界で今日も',
 '居場所をずっと探している',
 '死にたい\u3000と\u3000生きたい',
 'の間で何度も何度も迷いながら',
 '',
 '生まれてきた命には',
 'せめて愛を、愛\u3000を',
 'いつか優しくなれるように',
 'いつか優しい朝が来るように',
 '',
 'ハッピーバースディ',
 'ハッピーバースディ',
 'アンハッピーバースディ',
 'トゥ

In [15]:
text3 = " ".join(text2)

In [16]:
text3

'人はみんな、幸福を願い もれずに私もその輪を抜け出せない  誰もが不幸になどなりたくないと 一つしかないその席を取り合った  選ばれなかった命を 弔うことすら出来ないままで 私は今日も白々しく 生きている 歌ってる 顔の見えない誰かに謝りながら  パパとママが愛し合って 産まれてから20年が経った  何人に愛され 何人を傷付けてきたんだろう わたしは、わたしは、答えられない  選ばれたかった誰かが 見れたかもしれない光の色を 私は今日も探している 死にたいと生きたいの間を 何度も何度も、行き来しながら  今日は誰かの誕生日で そして同時にあなたの命日です ふとした時に思い出してそして いつかは忘れてしまうでしょう 死のうと思って止めたあとの 死ねずに吸い込んだこの息で 私は歌を歌っている 行きたい場所などどこにもなくて 生まれた意味はわからなくても せめて\u3000せめて せめて\u3000せめて\u3000せめて  ハッピーバースディ ハッピーバースディ アンハッピーバースディ トゥーユー  ハッピーバースディ ハッピーバースディ アンハッピーバースディ トゥーユー  選ばれなかった命を 弔うことすら出来ないままで 私は今日も願っている 生きていて、と 死なないで、と 何度も何度も私は叫ぶよ  選ばれたかった誰かと それでも続いてく世界で今日も 居場所をずっと探している 死にたい\u3000と\u3000生きたい の間で何度も何度も迷いながら  生まれてきた命には せめて愛を、愛\u3000を いつか優しくなれるように いつか優しい朝が来るように  ハッピーバースディ ハッピーバースディ アンハッピーバースディ トゥーユー  ハッピーバースディ ハッピーバースディ アンハッピーバースディ トゥーユー'

## Write Text File

In [18]:
filename = 'output-data/flat-music.txt'
file = open(filename, mode='w')# 'w' ทำการเลือกโหมดเขียน
file.write(text3)
file.close()

## Read Flat File CSV via Numpy

In [19]:
import numpy as np

In [20]:
filename = 'input-data/mnist_kaggle_some_rows.csv'

In [21]:
data = np.loadtxt(filename, delimiter=',')

In [22]:
data

array([[ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 1.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 2.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 5.,  0.,  0., ...,  0.,  0.,  0.]])

## Skip Row

In [23]:
data2 = np.loadtxt(filename, delimiter=',', skiprows=1)

In [24]:
data2

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 4.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 2.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 5.,  0.,  0., ...,  0.,  0.,  0.]])

## Use specific Column

In [25]:
data3 = np.loadtxt(filename, delimiter=',', skiprows=1, usecols=[0,2])

In [26]:
data3

array([[ 0.,  0.],
       [ 1.,  0.],
       [ 4.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 7.,  0.],
       [ 3.,  0.],
       [ 5.,  0.],
       [ 3.,  0.],
       [ 8.,  0.],
       [ 9.,  0.],
       [ 1.,  0.],
       [ 3.,  0.],
       [ 3.,  0.],
       [ 1.,  0.],
       [ 2.,  0.],
       [ 0.,  0.],
       [ 7.,  0.],
       [ 5.,  0.],
       [ 8.,  0.],
       [ 6.,  0.],
       [ 2.,  0.],
       [ 0.,  0.],
       [ 2.,  0.],
       [ 3.,  0.],
       [ 6.,  0.],
       [ 9.,  0.],
       [ 9.,  0.],
       [ 7.,  0.],
       [ 8.,  0.],
       [ 9.,  0.],
       [ 4.,  0.],
       [ 9.,  0.],
       [ 2.,  0.],
       [ 1.,  0.],
       [ 3.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 4.,  0.],
       [ 9.,  0.],
       [ 1.,  0.],
       [ 4.,  0.],
       [ 4.,  0.],
       [ 2.,  0.],
       [ 6.,  0.],
       [ 3.,  0.],
       [ 7.,  0.],
       [ 7.,  0.],
       [ 4.,  0.],
       [ 7.,  0.],
       [ 5.,  0.],
       [ 1.,  0.],
       [ 9.,

In [27]:
type(data3)

numpy.ndarray

In [34]:
type(data3[0][0])

numpy.float64

In [35]:
data3[0][0]

0.0

## Customize Import Type

In [30]:
data4 = np.loadtxt(filename, delimiter=',', skiprows=1, usecols=[0,2], dtype=str)

In [31]:
type(data4)

numpy.ndarray

In [33]:
type(data4[0][0])

numpy.str_

In [36]:
data4[0][0]

'0.0'

## Save Flat File via Numpy

In [46]:
save_filename = 'output-data/flat-mnist.csv'

In [47]:
np.savetxt(save_filename, data3,delimiter=',')

## Read Flat File via Pandas

In [1]:
import pandas as pd

In [2]:
filename = 'input-data/titanic_sub.csv'

In [3]:
df = pd.read_csv(filename)

In [5]:
df.head(10)

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch  \
0            1         0       3    male  22.0      1      0   
1            2         1       1  female  38.0      1      0   
2            3         1       3  female  26.0      0      0   
3            4         1       1  female  35.0      1      0   
4            5         0       3    male  35.0      0      0   
5            6         0       3    male   NaN      0      0   
6            7         0       1    male  54.0      0      0   
7            8         0       3    male   2.0      3      1   
8            9         1       3  female  27.0      0      2   
9           10         1       2  female  14.0      1      0   

             Ticket     Fare Cabin Embarked  
0         A/5 21171   7.2500   NaN        S  
1          PC 17599  71.2833   C85        C  
2  STON/O2. 3101282   7.9250   NaN        S  
3            113803  53.1000  C123        S  
4            373450   8.0500   NaN        S  
5            330877   8.4583   NaN        Q  
6             17463  51.8625   E46        S  
7            349909  21.0750   NaN        S  
8            347742  11.1333   NaN        S  
9            237736  30.0708   NaN        C

In [48]:
dfHead = df.head()

## Save Flat File via Pandas

In [49]:
save_filepath = 'output-data/titanic_head.csv'

In [50]:
dfHead.to_csv(save_filepath)

## Pandas Skip rows

In [13]:
filename = 'input-data/titanic_sub.csv'
df_skip = pd.read_csv(filename, skiprows=range(1, 10))

In [14]:
df_skip.head(10)

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch     Ticket  \
0           10         1       2  female  14.0      1      0     237736   
1           11         1       3  female   4.0      1      1    PP 9549   
2           12         1       1  female  58.0      0      0     113783   
3           13         0       3    male  20.0      0      0  A/5. 2151   
4           14         0       3    male  39.0      1      5     347082   
5           15         0       3  female  14.0      0      0     350406   
6           16         1       2  female  55.0      0      0     248706   
7           17         0       3    male   2.0      4      1     382652   
8           18         1       2    male   NaN      0      0     244373   
9           19         0       3  female  31.0      1      0     345763   

      Fare Cabin Embarked  
0  30.0708   NaN        C  
1  16.7000    G6        S  
2  26.5500  C103        S  
3   8.0500   NaN        S  
4  31.2750   NaN        S  
5   7.8542   NaN        S  
6  16.0000   NaN        S  
7  29.1250   NaN        Q  
8  13.0000   NaN        S  
9  18.0000   NaN        S

In [15]:
df_skip2 = pd.read_csv(filename, skiprows=[1,2,3,4,5])

In [16]:
df_skip2.head(10)

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch     Ticket  \
0            6         0       3    male   NaN      0      0     330877   
1            7         0       1    male  54.0      0      0      17463   
2            8         0       3    male   2.0      3      1     349909   
3            9         1       3  female  27.0      0      2     347742   
4           10         1       2  female  14.0      1      0     237736   
5           11         1       3  female   4.0      1      1    PP 9549   
6           12         1       1  female  58.0      0      0     113783   
7           13         0       3    male  20.0      0      0  A/5. 2151   
8           14         0       3    male  39.0      1      5     347082   
9           15         0       3  female  14.0      0      0     350406   

      Fare Cabin Embarked  
0   8.4583   NaN        Q  
1  51.8625   E46        S  
2  21.0750   NaN        S  
3  11.1333   NaN        S  
4  30.0708   NaN        C  
5  16.7000    G6        S  
6  26.5500  C103        S  
7   8.0500   NaN        S  
8  31.2750   NaN        S  
9   7.8542   NaN        S

## Pandas Import certain columns 

In [17]:
df_col = pd.read_csv(filename, usecols=["Survived", "Pclass", "Age", "Ticket"])

In [18]:
df_col.head()

Survived  Pclass   Age            Ticket
0         0       3  22.0         A/5 21171
1         1       1  38.0          PC 17599
2         1       3  26.0  STON/O2. 3101282
3         1       1  35.0            113803
4         0       3  35.0            373450

## Pandas Change column names

In [19]:
df_col.columns = ['รอดไม่รอด', 'ระดับชั้น', 'อายุ', 'รหัสตั๋ว']

In [20]:
df_col.head()

รอดไม่รอด  ระดับชั้น  อายุ          รหัสตั๋ว
0          0          3  22.0         A/5 21171
1          1          1  38.0          PC 17599
2          1          3  26.0  STON/O2. 3101282
3          1          1  35.0            113803
4          0          3  35.0            373450

In [21]:
df_col.dtypes

รอดไม่รอด      int64
ระดับชั้น      int64
อายุ         float64
รหัสตั๋ว      object
dtype: object

## Change Type to object

In [24]:
df_col['อายุ'] = df_col['อายุ'].astype(object)

In [25]:
df_col.dtypes

รอดไม่รอด     int64
ระดับชั้น     int64
อายุ         object
รหัสตั๋ว     object
dtype: object

## Read Excel File via Pandas

In [26]:
filepath_excel = 'input-data/battledeath.xlsx'
df_excel = pd.ExcelFile(filepath_excel)
df_excel.sheet_names # Check ว่ามีชื่อ sheet อะไรบ้าง

['2002', '2004']

In [27]:
df_2002 = df_excel.parse('2002')
df_2004 = df_excel.parse('2004')

In [28]:
df_2002.head()

War, age-adjusted mortality due to       2002
0                        Afghanistan  36.083990
1                            Albania   0.128908
2                            Algeria  18.314120
3                            Andorra   0.000000
4                             Angola  18.964560

In [29]:
df_2004.head()

War(country)      2004
0  Afghanistan  9.451028
1      Albania  0.130354
2      Algeria  3.407277
3      Andorra  0.000000
4       Angola  2.597931

## Save Excel File via Pandas

In [30]:
writer = pd.ExcelWriter('output-data/battledeath-output.xlsx')
df_2002.to_excel(writer,'2002')
df_2004.to_excel(writer,'2004')
writer.save()